module.exports = {
  $schema:
    "https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json",
  allowCompoundWords: true,
  caseSensitive: true,
  dictionaries: [
    "bash",
    "en_us",
    "en-gb",
    "fullstack",
    "html",
    "node",
    "npm",
    "softwareTerms",
    "typescript",
  ],
  ignorePaths: [
    "dist",
    "node_modules",
    "package.json",
    "pnpm-lock.yaml",
    ".gitignore",
    ".npmignore",
    "*.snap",
    "*.svg",
    "coverage",
    "*.log",
    "*.min.js",
    ".git",
    "cspell.config.cjs",
    "CHANGELOG.md",
    "dist-tarball",
  ],
  language: "en",
  useGitignore: true,
  words: [
    "AIBot",
    "AIBots",
    "Anthropic",
    "ChatGPT",
    "claude",
    "Cris",
    "IndexNow",
    "jsonld",
    "llms",
    "MassID",
    "massid",
    "mdx",
    "OAI",
    "Orama",
    "orama",
    "Perplexity",
    "pnpm",
    "releaserc",
    "schemaorg",
    "Santos",
    "Speakable",
    "tldr",
    "TRC",
    "tsup",
    "thursday",
    "tuesday",
    "vitest",
  ],
  ignoreRegExpList: ["/https?:\\/\\/[^\\s\"')]+/", "/\\b[0-9a-f]{8,}\\b/i"],
};
